trigger:
  branches:
    include:
    - '*'

variables:
- name: DOCKER_REGISTRY
  value: lm-devops-docker.artifactory.com
- name: major
  value: 0
- name: minor
  value: 0
- name: JFROG_CLI_OFFER_CONFIG
  value: "false"

stages:
- stage: ADO_INFRALM_SF
  displayName: Build ADO_INFRALM_SF container and helm chart
  jobs:
  - job: BuildLatest
    displayName: Build ADO AGENT INFRALM SF container image
    pool:
      name: 'linux vmss agent hosted'
      demands:
        - 'docker'
    workspace:
      clean: all
    timeoutInMinutes: 30
    steps:
      - task: replacetokens@3
        inputs:
          targetFiles: '**\config.json'
          encoding: 'auto'
          writeBOM: true
          actionOnMissing: 'continue'
          keepToken: false
          tokenPrefix: '#{'
          tokenSuffix: '}#'
          useLegacyPattern: false
          enableTelemetry: false
      - bash: |
          docker --config lm-ado-sf/ build --build-arg HELMPWD=HELMPWD --no-cache \
          -t $DOCKER_REGISTRY/lm-ado-agent-sf:latest \
          -t $DOCKER_REGISTRY/lm-ado-agent-sf:$(major).$(Build.BuildNumber) \
          lm-ado-sf/
        displayName: 'Docker Build'
